apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
  labels:
    app: keycloak
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi